stages :
  - install

dependencies:
  stage: install
  image: node:12-alpine
  cache:
    key:
      files:
        - yarn.lock
    paths:
      - node_modules
    policy: pull
  script:
    - npm install
